In [1]:
import numpy as np

In [ ]:
# 🌹 Q.1-->

arr = np.arange(start=2, stop=50, step=3)
print(arr)
#or
np.arange(2,50,3)

In [60]:
# 🍁 Q.2 -->

lst1 = []    
lst2 = []   
print("Enter lst1:")
for i in range(5):
    lst1.append(int(input())) 

print("Enter lst2:")
for i in range(5):
    lst2.append(int(input())) 

arr1= np.asarray(lst1)
arr2 =np.asarray(lst2)

print(np.concatenate((arr1, arr2)))
print(np.sort(np.concatenate((arr1, arr2))))


Enter lst1:
1
20
100
2
3
Enter lst2:
1000
2
3
76
45
[   1   20  100    2    3 1000    2    3   76   45]
[   1    2    2    3    3   20   45   76  100 1000]


In [46]:
# 🍂 Q.3 -->

x = np.arange(10).reshape(2,5)
print(x)
print(x.ndim)
print(x.size)
print(x.shape)


[[0 1 2 3 4]
 [5 6 7 8 9]]
2
10
(2, 5)


In [59]:
# 🌻 Q.4 -->

y = np.array([1,2,3,4,5,6])
print(y)

print("\n",y[:, np.newaxis])
print("\n",y[np.newaxis, :])

print("\n",np.expand_dims(y, axis=0))
print("\n",np.expand_dims(y, axis=1))
print("\n",np.expand_dims(y, axis=(0, 1)))



[1 2 3 4 5 6]

 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

 [[1 2 3 4 5 6]]

 [[1 2 3 4 5 6]]

 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

 [[[1 2 3 4 5 6]]]


In [66]:
# 🌼 Q.5 -->

sq1 = np.arange(11, 20).reshape((3, 3))
print(sq1)
sq2 = np.arange(21, 30).reshape((3, 3))
print("\n",sq2)

print("\n",np.hstack((sq1, sq2)))
print("\n",np.vstack((sq1, sq2)))


[[11 12 13]
 [14 15 16]
 [17 18 19]]

 [[21 22 23]
 [24 25 26]
 [27 28 29]]

 [[11 12 13 21 22 23]
 [14 15 16 24 25 26]
 [17 18 19 27 28 29]]

 [[11 12 13]
 [14 15 16]
 [17 18 19]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


In [81]:
# 🌺 Q.6 -->

lst = []
lst = [int(item) for item in input("Enter the list items : ").split()]
unique, count = np.unique(lst,  return_counts = True) 
print(np.asarray((unique, count)).T)

Enter the list items : 1 2 3 4 10 100 100 2 3 4 5 6 7 8 9 0 12 
[[  0   1]
 [  1   1]
 [  2   2]
 [  3   2]
 [  4   2]
 [  5   1]
 [  6   1]
 [  7   1]
 [  8   1]
 [  9   1]
 [ 10   1]
 [ 12   1]
 [100   2]]
